version: '3.7'
services:
  db:
    build: docker/mysql
    entrypoint: docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_TEST_DATABASE: '${DB_DATABASE}_test'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      TZ: Asia/Tokyo
    ports:
      - '${DOCKER_DB_PUBLIC_PORT:-3306}:3306'

  web:
    build: docker/web
    environment:
      TZ: Asia/Tokyo
      APACHE_DOCUMENT_ROOT: '/var/www/project/public'
      APACHE_LOG_DIR: '/var/www/project/storage/logs'
      PHP_UPLOAD_MAX_FILESIZE: '${PHP_UPLOAD_MAX_FILESIZE:-60M}'
      PHP_POST_MAX_SIZE: '${PHP_POST_MAX_SIZE:-60M}'
      PHP_XDEBUG_REMOTE_ENABLE: '${PHP_XDEBUG_REMOTE_ENABLE:-on}'
      PHP_XDEBUG_REMOTE_PORT: '${PHP_XDEBUG_REMOTE_PORT:-9000}'
      PHP_XDEBUG_REMOTE_HOST: '${PHP_XDEBUG_REMOTE_HOST:-host.docker.internal}'
      PHP_XDEBUG_REMOTE_AUTO_START: '${PHP_XDEBUG_REMOTE_AUTO_START:-off}'
      PHP_XDEBUG_REMOTE_CONNECT_BACK: '${PHP_XDEBUG_REMOTE_CONNECT_BACK:-off}'
      PHP_XDEBUG_IDEKEY: '${PHP_XDEBUG_IDEKEY:-IDEA}'
      PHP_XDEBUG_PROFILER_ENABLE: '${PHP_XDEBUG_PROFILER_ENABLE:-off}'
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: '${PHP_XDEBUG_PROFILER_OUTPUT_DIR:-/tmp}'
      PHP_XDEBUG_PROFILER_ENABLE_TRIGGER: '${PHP_XDEBUG_PROFILER_ENABLE_TRIGGER:-on}'
    volumes:
      - '.:/var/www/project'
    depends_on:
      - db
    command: /bin/bash -c "
      composer install &&
      /wait-for-it/wait-for-it.sh db:3306 -- php /var/www/project/artisan migrate:fresh --seed &&
      apache2-foreground
      "
    ports:
      - '${DOCKER_WEB_PUBLIC_PORT:-80}:80'
